name: Keploy API Testing

on:
  push:
    branches: [main]
  pull_request:

jobs:
  keploy-test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Start app
        run: |
          npm run start & 
          sleep 15

      - name: Run Keploy tests
        run: curl -sSfL https://get.keploy.io/install.sh | sh && keploy test -c "curl -X GET https://dragon-ball-api-grlr.onrender.com/random" -g
